#注册中心的名字
spring:
  application:
    name: myEureka
#服务端口
server:
  port: 7890
#注册中心相关配置
eureka:
  server:
    #配置关闭自我保护，并按需配置Eureka Server清理无效节点的时间间隔（5000ms）
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    #不将自己注册到注册中心
    register-with-eureka: false
    #因为自己是注册中心，因此不用检索服务信息
    fetch-registry: false
    #注册中心地址
    service-url:
      defaultZone: http://localhost:7890/Eureka-Client/
  instance:
    prefer-ip-address: true
    #注册中心的名字
    spring:
      application:
        name: my-eureka
    #服务端口
    server:
      port: 7890
    #注册中心相关配置
    eureka:
      server:
        # 配置关闭自我保护，并按需配置Eureka Server清理无效节点的时间间隔（5000ms）。
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 5000
      client:
        # 不将自己注册到注册中心
        register-with-eureka: false #fasle:
        # 因为自己是注册中心，因此不用检索服务信息
        fetch-registry: false        #true： Cannot execute request on any know server
        # 注册中心的地址
        service-url:
          defaultZone: http://localhost:7890/eurekaClient/
      instance:
        prefer-ip-address: true
      spring:
       application:
        name: client-test
      #服务端口
    Client:
      port: 10212
     # 注册中心地址
